const events = [
  {
    id: "1",
    eventTitle: "Tech Whiz",
    date: "20th March 2023",
    details: [
      "quiz based around tech",
      "multi-round setup",
      "knockout rounds",
      "Individual and team participation",
      "certificate to the winners",
    ],
    duration: "2 hours",
    rounds: [
      "Round 1 - individual participation",
      "Round 2 - team round (buzzer round)",
    ],
  },
  {
    id: "2",
    eventTitle: "Fashionova",
    date: "20th March 2023",
    details: [
      "sudents will be wearing indian tradiional clothes",
      "students can register themselves for a fashion contest",
      "individual participation",
      "winners will get assured prizes",
    ],
    duration: "TBD",
    rounds: [],
  },
  {
    id: "3",
    eventTitle: "Code Warz",
    date: "21st March 2023",
    details: [
      "competitive programming contest",
      "single round event",
      "Individual participation",
      "certificate to the winners",
    ],
    duration: "2 hours",
    rounds: [],
  },
  {
    id: "4",
    eventTitle: "Junkyard Junkies",
    date: "21st March 2023",
    details: [
      "Robot war event",
      "multi-round setup",
      "Individual/team participation",
      "trophies to the winners",
    ],
    duration: "TBD",
    rounds: ["Round 1 - Circuit Run", "Round 2 - Arena War"],
  },
  {
    id: "5",
    eventTitle: "Web Dev Set",
    date: "22nd March 2023",
    details: [
      "WEB DEVELOPMENT HACKATHON",
      "INDIVIDUAL/TEAM PARTICIPATION",
      "BRING YOUR OWN MACHINE",
      "DEVELOPMENT BASED ON THEME",
      "CERTIFICATE TO THE WINNERS",
    ],
    duration: "3 hours",
    rounds: [],
  },
  {
    id: "6",
    eventTitle: "Keyboard Warriors",
    date: "22nd march 2023",
    details: [
      "SPEED TYPING CONTEST",
      "BRING YOUR OWN MACHINES",
      "CERTIFICATE TO THE WINNERS",
    ],
    duration: "TBD",
    rounds: [],
  },
  {
    id: "9",
    eventTitle: "Rebootal",
    date: "23rd march 2023",
    details: [
      "DEBATE BASED ON TECH TRENDS",
      "INDIVIDUAL PARTICIPATION",
      "TIME LIMIT: 3 MINUTES",
      "NO LANGUAGE BARRIER",
      "LOTTERY BASED MOTION CHOICE",
      "CERTIFICATE TO THE WINNERS",
    ],
    duration: "2 hours",
    rounds: [],
  },
  {
    id: "10",
    eventTitle: "CrossHair Combat",
    date: "23rd march 2023",
    details: [
      "VALORANT  (TDM)",
      "BGMI MOBILE (TDM)",
      "BRING YOUR OWN MACHINE",
      "AWARDS TO WINNERS",
    ],
    duration: "TBD",
    rounds: [],
  },
  {
    id: "11",
    eventTitle: "Hack Hunt",
    date: "24th march 2023",
    details: [
      "TREASURE HUNT",
      "8 PARTICIPANTS PER TEAM",
      "BASED ON CRYPTOGRAPHY",
      "CHALLENGE YOUR PROBLEM SOLVING SKILLS",
      "TEAM PARTICIPATION",
      "CERTIFICATE TO THE WINNERS",
    ],
    duration: "TBD",
    rounds: [],
  },
  {
    id: "12",
    eventTitle: "Rubix Cubix",
    date: "24th march 2023",
    details: ["SPEED RUBIK'S CUBE SOLVING", "CERTIFICATE TO THE WINNERS"],
    duration: "TBD",
    rounds: [],
  },
  {
    id: "13",
    eventTitle: "Expert Connect",
    date: "25th march 2023",
    details: [
      "LISTEN TO INDUSTRY EXPERTS",
      "LEARN ABOUT NEW TRENDS IN TECH ",
      "OPEN TO ALL",
      "QnA SESSION",
      "NETWORKING OPPORTUNITY",
    ],
    duration: "TBD",
    rounds: [],
  },
  {
    id: "14",
    eventTitle: "Biz Wiz",
    date: "23rd march 2023",
    details: [
      "PRESENT YOUR PITCH DECK",
      "AT LEAST 3, AT MOST 4 MEMBERS",
      "OPPORTUNITY TO MEET INVESTORS",
      "TIME LIMIT : 5 MINUTES",
      "CERTIFICATE TO THE WINNERS",
    ],
    duration: "TBD",
    rounds: [],
  },
  {
    id: "15",
    eventTitle: "Lens Sense",
    date: "20th-25th March 2023",
    details: [
      "PHOTOGRAPHY COMPETITION",
      "SUBMIT 15 PHOTOGRAPHS ON LAST DAY",
      "BRING YOUR OWN CAMERA",
      "AWARD TO THE WINNERS",
    ],
    duration: "6 days",
    rounds: [],
  },
  {
    id: "16",
    eventTitle: "Film Fever",
    date: "20th-24th March 2023",
    details: [
      "FILM MAKING COMPETITION",
      "SUBMIT SHORT FILM ON LAST DAY",
      "BRING YOUR OWN CAMERA",
      "FILM DURATION : 2 MINUTES",
      "AWARD TO THE WINNERS",
    ],
    duration: "5 days",
    rounds: [],
  },
  {
    id: "17",
    eventTitle: "Chill vibes",
    date: "20th-25th march 2023",
    details: [
      "OPEN MIC",
      "STAND-UP COMEDY",
      "SINGING",
      "POETRY/SHAYARI",
      "INSTRUMENTAL JAMMING",
    ],
    duration: "6 days",
    rounds: [],
  },
  {
    id: "18",
    eventTitle: "Side Events",
    date: "20th-25th march 2023",
    details: [
      "FUN GAMES",
      "T-SHIRT DESIGN COMPETITION",
      "MASK OFF (FACE PAINTING)",
      "GRAFFITI CONTEST",
      "and many other games...",
    ],
    duration: "5 days",
    rounds: [],
  },
];

export default events;
